language: android
jdk: oraclejdk7

before_install:
 - chmod +x gradlew


env:
  matrix:
    - ANDROID_TARGET=android-16  ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-19.0.0
    - extra 

script: ./gradlew
